[package]
name = "tokio-postgres"
version = "0.3.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A native PostgreSQL driver using Tokio"
repository = "https://github.com/sfackler/rust-postgres"
readme = "../README.md"
keywords = ["database", "postgres", "postgresql", "sql", "async"]
categories = ["database"]

[package.metadata.docs.rs]
features = [
    "with-bit-vec-0.5",
    "with-chrono-0.4",
    "with-eui48-0.3",
    "with-geo-0.10",
    "with-serde_json-1",
    "with-uuid-0.6",
]

[badges]
circle-ci = { repository = "sfackler/rust-postgres" }

[features]
"with-bit-vec-0.5" = ["bit-vec"]
"with-chrono-0.4" = ["chrono"]
"with-eui48-0.3" = ["eui48"]
"with-geo-0.10" = ["geo"]
with-serde_json-1 = ["serde", "serde_json"]
"with-uuid-0.6" = ["uuid"]

[dependencies]
antidote = "1.0"
bytes = "0.4"
fallible-iterator = "0.1.3"
futures = "0.1.7"
futures-cpupool = "0.1"
log = "0.4"
phf = "0.7.23"
postgres-protocol = { version = "0.3.0", path = "../postgres-protocol" }
state_machine_future = "0.1.7"
tokio-codec = "0.1"
tokio-io = "0.1"
void = "1.0"

bit-vec = { version = "0.5", optional = true }
chrono = { version = "0.4", optional = true }
eui48 = { version = "0.3", optional = true }
geo = { version = "0.10", optional = true }
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
uuid = { version = "0.6", optional = true }

[dev-dependencies]
tokio = "0.1.7"
env_logger = "0.5"
