[package]
name = "tokio-postgres"
version = "0.4.0-rc.3"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "A native, asynchronous PostgreSQL client"
repository = "https://github.com/sfackler/rust-postgres"
readme = "../README.md"
keywords = ["database", "postgres", "postgresql", "sql", "async"]
categories = ["database"]

[lib]
test = false

[package.metadata.docs.rs]
all-features = true

[badges]
circle-ci = { repository = "sfackler/rust-postgres" }

[features]
default = ["runtime"]
runtime = ["tokio/rt-full", "tokio/tcp", "tokio/uds", "tokio-executor", "lazy_static"]

"with-bit-vec-0_6" = ["postgres-types/with-bit-vec-0_6"]
"with-chrono-0_4" = ["postgres-types/with-chrono-0_4"]
"with-eui48-0_4" = ["postgres-types/with-eui48-0_4"]
"with-geo-types-0_4" = ["postgres-types/with-geo-types-0_4"]
with-serde_json-1 = ["postgres-types/with-serde_json-1"]
"with-uuid-0_7" = ["postgres-types/with-uuid-0_7"]

[dependencies]
bytes = "0.4"
fallible-iterator = "0.2"
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await"] }
log = "0.4"
parking_lot = "0.9"
percent-encoding = "1.0"
pin-utils = "=0.1.0-alpha.4"
phf = "0.7.23"
postgres-protocol = { version = "0.4.1", path = "../postgres-protocol" }
postgres-types = { version = "0.1.0", path = "../postgres-types" }
tokio = { version = "=0.2.0-alpha.6", default-features = false, features = ["io", "codec"] }

tokio-executor = { version = "=0.2.0-alpha.6", optional = true }
lazy_static = { version = "1.0", optional = true }

[dev-dependencies]
tokio = "=0.2.0-alpha.6"
env_logger = "0.5"
