[package]
name = "tokio-postgres"
version = "0.4.0-rc.3"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "A native, asynchronous PostgreSQL client"
repository = "https://github.com/sfackler/rust-postgres"
readme = "../README.md"
keywords = ["database", "postgres", "postgresql", "sql", "async"]
categories = ["database"]

[lib]
test = false

[package.metadata.docs.rs]
all-features = true

[badges]
circle-ci = { repository = "sfackler/rust-postgres" }

[features]
default = ["runtime"]
runtime = ["tokio-tcp", "tokio-timer", "tokio-uds", "futures-cpupool", "lazy_static"]

"with-bit-vec-0_6" = ["bit-vec-06"]
"with-chrono-0_4" = ["chrono-04"]
"with-eui48-0_4" = ["eui48-04"]
"with-geo-types-0_4" = ["geo-types-04"]
with-serde_json-1 = ["serde-1", "serde_json-1"]
"with-uuid-0_7" = ["uuid-07"]

[dependencies]
antidote = "1.0"
bytes = "0.4"
fallible-iterator = "0.2"
futures = "0.1.7"
log = "0.4"
percent-encoding = "1.0"
phf = "0.7.23"
postgres-protocol = { version = "0.4.1", path = "../postgres-protocol" }
state_machine_future = "0.2"
tokio-codec = "0.1"
tokio-io = "0.1"

tokio-tcp = { version = "0.1", optional = true }
futures-cpupool = { version = "0.1", optional = true }
lazy_static = { version = "1.0", optional = true }
tokio-timer = { version = "0.2", optional = true }

bit-vec-06 = { version = "0.6.1", package = "bit-vec", optional = true }
chrono-04 = { version = "0.4", package = "chrono", optional = true }
eui48-04 = { version = "0.4", package = "eui48", optional = true }
geo-types-04 = { version = "0.4", package = "geo-types", optional = true }
serde-1 = { version = "1.0", package = "serde", optional = true }
serde_json-1 = { version = "1.0", package = "serde_json", optional = true }
uuid-07 = { version = "0.7", package = "uuid", optional = true }

[target.'cfg(unix)'.dependencies]
tokio-uds = { version = "0.2", optional = true }

[dev-dependencies]
tokio = "0.1.7"
env_logger = "0.5"
