[package]
name = "tokio-postgres"
version = "0.3.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "A native PostgreSQL driver using Tokio"
repository = "https://github.com/sfackler/rust-postgres"
readme = "../README.md"
keywords = ["database", "postgres", "postgresql", "sql", "async"]
categories = ["database"]

[package.metadata.docs.rs]
features = [
    "with-bit-vec-0.5",
    "with-chrono-0.4",
    "with-eui48-0.3",
    "with-geo-0.10",
    "with-serde_json-1",
    "with-uuid-0.6",
    "with-openssl",
]

[badges]
circle-ci = { repository = "sfackler/rust-postgres" }

[features]
"with-bit-vec-0.5" = ["postgres-shared/with-bit-vec-0.5"]
"with-chrono-0.4" = ["postgres-shared/with-chrono-0.4"]
"with-eui48-0.3" = ["postgres-shared/with-eui48-0.3"]
"with-geo-0.10" = ["postgres-shared/with-geo-0.10"]
"with-serde_json-1" = ["postgres-shared/with-serde_json-1"]
"with-uuid-0.6" = ["postgres-shared/with-uuid-0.6"]

with-openssl = ["tokio-openssl", "openssl"]

[dependencies]
bytes = "0.4"
fallible-iterator = "0.1.3"
futures = "0.1.7"
futures-state-stream = "0.2"
postgres-protocol = { version = "0.3.0", path = "../postgres-protocol" }
postgres-shared = { version = "0.4.0", path = "../postgres-shared" }
tokio-core = "0.1.8"
tokio-dns-unofficial = "0.1"
tokio-io = "0.1"

tokio-openssl = { version = "0.2", optional = true }
openssl = { version = "0.10", optional = true }

[target.'cfg(unix)'.dependencies]
tokio-uds = "0.1"
