[package]
name = "tokio-postgres"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "A native PostgreSQL driver using Tokio"
repository = "https://github.com/sfackler/rust-postgres"
documentation = "https://docs.rs/postgres-tokio/0.13.4/postgres_tokio"
readme = "../README.md"

[features]
with-bit-vec = ["postgres-shared/with-bit-vec"]
with-chrono = ["postgres-shared/with-chrono"]
with-eui48 = ["postgres-shared/with-eui48"]
with-rustc-serialize = ["postgres-shared/with-rustc-serialize"]
with-serde_json = ["postgres-shared/with-serde_json"]
with-time = ["postgres-shared/with-time"]
with-uuid = ["postgres-shared/with-uuid"]

with-openssl = ["tokio-openssl", "openssl"]

[dependencies]
fallible-iterator = "0.1.3"
futures = "0.1.7"
futures-state-stream = "0.1"
postgres-shared = { path = "../postgres-shared" }
postgres-protocol = "0.2"
tokio-core = "0.1"
tokio-dns-unofficial = "0.1"
tokio-uds = "0.1"

tokio-openssl = { version = "0.1", optional = true }
openssl = { version = "0.9", optional = true }
