[package]
name = "tokio-postgres"
version = "0.4.0-rc.3"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "A native, asynchronous PostgreSQL client"
repository = "https://github.com/sfackler/rust-postgres"
readme = "../README.md"
keywords = ["database", "postgres", "postgresql", "sql", "async"]
categories = ["database"]

[lib]
test = false

[package.metadata.docs.rs]
all-features = true

[badges]
circle-ci = { repository = "sfackler/rust-postgres" }

[features]
default = ["runtime"]
runtime = ["tokio/rt-full", "tokio/tcp", "tokio/uds", "tokio-threadpool", "lazy_static"]

"with-bit-vec-0_5" = ["bit-vec-05"]
"with-chrono-0_4" = ["chrono-04"]
"with-eui48-0_4" = ["eui48-04"]
"with-geo-types-0_4" = ["geo-types-04"]
with-serde_json-1 = ["serde-1", "serde_json-1"]
"with-uuid-0_7" = ["uuid-07"]

[dependencies]
bytes = "0.4"
fallible-iterator = "0.2"
futures-preview = { version = "0.3.0-alpha.17", features = ["nightly", "async-await"] }
log = "0.4"
parking_lot = "0.9"
percent-encoding = "1.0"
phf = "0.7.23"
postgres-protocol = { version = "0.4.1", path = "../postgres-protocol" }
tokio = { git = "https://github.com/tokio-rs/tokio", default-features = false, features = ["io", "codec"] }

tokio-threadpool = { git = "https://github.com/tokio-rs/tokio", optional = true }
lazy_static = { version = "1.0", optional = true }

bit-vec-05 = { version = "0.5", package = "bit-vec", optional = true }
chrono-04 = { version = "0.4", package = "chrono", optional = true }
eui48-04 = { version = "0.4", package = "eui48", optional = true }
geo-types-04 = { version = "0.4", package = "geo-types", optional = true }
serde-1 = { version = "1.0", package = "serde", optional = true }
serde_json-1 = { version = "1.0", package = "serde_json", optional = true }
uuid-07 = { version = "0.7", package = "uuid", optional = true }

[dev-dependencies]
tokio = { git = "https://github.com/tokio-rs/tokio" }
env_logger = "0.5"
