language: rust
cache: cargo
sudo: required
rust:
- nightly
- 1.13.0
addons:
  postgresql: 9.4
before_script:
- "./.travis/setup.sh"
script:
- cargo test --manifest-path=postgres/Cargo.toml
- cargo test --manifest-path=postgres/Cargo.toml --features "$(cargo read-manifest --manifest-path=postgres/Cargo.toml | jq -r '.features|keys|map(select(. != "with-security-framework" and . != "with-schannel"))|join(" ")')"
- cargo test --manifest-path=tokio-postgres/Cargo.toml
