language: rust
env:
  global:
    - secure: Dl8GH7HCtwf0iG0EiBlQprZ5wQ7Wz8lfsMGxCSfTCjWoCbYK5+B5xuPnSaj8UYbrbXHmaZms23kSc5ZgQixuKs3zMCRDuEX1safT+t3AlhY/5/T3uyUWd1bv2Brw4TZg7M0Dubsu+3+3jNcDYv6vp+YWUNlKUcxjcX4EPrY0FKI=
  matrix:
    - FEATURES=""
    - FEATURES="uuid_type"
addons:
  postgresql: 9.3
before_script:
  - ./.travis/setup.sh
script:
  - cargo test --features "$FEATURES"
  - cargo doc --no-deps --features "uuid_type"
after_script:
  - mv target/doc .
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
