language: rust
cache: cargo
sudo: required
rust:
- nightly
- 1.10.0
addons:
  postgresql: 9.4
before_script:
- "./.travis/setup.sh"
script:
- cargo test
- cargo test --features "$(cargo read-manifest | jq -r '.features|keys|map(select(. != "with-security-framework"))|join(" ")')"
