[package]

name = "rust-postgres"
version = "0.0.0"
authors = [ "Steven Fackler <sfackler@gmail.com>" ]

[[lib]]

name = "postgres"
path = "src/lib/lib.rs"

[dependencies.openssl]

git = "https://github.com/sfackler/rust-openssl"
rev = "8696b091402f67a655c3b924c118392cb67540a3"

[dependencies.phf]

git = "https://github.com/sfackler/rust-phf"
rev = "cb4ed93175b656f442802c27e039add8e2b86723"

[dependencies.phf_mac]

git = "https://github.com/sfackler/rust-phf"
rev = "cb4ed93175b656f442802c27e039add8e2b86723"
