[package]

name = "rust-postgres"
version = "0.0.0"
authors = [ "Steven Fackler <sfackler@gmail.com>" ]

[[lib]]

name = "postgres"
path = "src/lib/lib.rs"
test = false

[[test]]

name = "test"
path = "src/test/test.rs"

[dependencies.openssl]

git = "https://github.com/sfackler/rust-openssl"
rev = "8696b091402f67a655c3b924c118392cb67540a3"

[dependencies.phf]

git = "https://github.com/sfackler/rust-phf"
rev = "60f391c38b548f5134addb116d2adcfa18ba3367"

[dependencies.phf_mac]

git = "https://github.com/sfackler/rust-phf"
rev = "60f391c38b548f5134addb116d2adcfa18ba3367"
