[package]
name = "postgres"
version = "0.0.0"
authors = [ "Steven Fackler <sfackler@gmail.com>" ]

[lib]
name = "postgres"
path = "src/lib.rs"
test = false

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies.openssl]
git = "https://github.com/sfackler/rust-openssl"
rev = "cd40d25cb5721064c5c2002c41a616d2dba7399a"

[dependencies.phf]
git = "https://github.com/sfackler/rust-phf"
rev = "af0a11c92bd531c9677bef31f6a6d8c4b59ad29b"

[dependencies.phf_mac]
git = "https://github.com/sfackler/rust-phf"
rev = "af0a11c92bd531c9677bef31f6a6d8c4b59ad29b"
