[package]
name = "postgres"
version = "0.0.1"
authors = [ "Steven Fackler <sfackler@gmail.com>" ]
license = "MIT"
description = "A native PostgreSQL driver"
repository = "https://github.com/sfackler/rust-postgres"
documentation = "https://sfackler.github.io/doc/postgres"
readme = "README.md"
keywords = ["database", "sql"]

[lib]
name = "postgres"
path = "src/lib.rs"
test = false

[[test]]
name = "test"
path = "tests/test.rs"

[features]
default = ["uuid", "time"]

[dependencies.openssl]
git = "https://github.com/sfackler/rust-openssl"

[dependencies]
phf = "*"
phf_mac = "*"

[dependencies.uuid]
git = "https://github.com/rust-lang/uuid"
optional = true

[dependencies.time]
git = "https://github.com/rust-lang/time"
optional = true

[dev-dependencies]
url = "*"

