[package]

name = "rust-postgres"
version = "0.0.0"
authors = [ "Steven Fackler <sfackler@gmail.com>" ]

[[lib]]

name = "postgres"
path = "src/lib.rs"

[dependencies.openssl]

git = "https://github.com/sfackler/rust-openssl"
ref = "5fb236128c4c552ace49c2d1f72a8996ee8d05d6"

[dependencies.phf_mac]

git = "https://github.com/sfackler/rust-phf"
ref = "bfd8fa2d4c494b1dbbaf6a57ee195cd8c8c0ab76"

