[package]

name = "rust-postgres"
version = "0.0.0"
authors = [ "Steven Fackler <sfackler@gmail.com>" ]

[[lib]]

name = "postgres"
path = "src/lib.rs"

[dependencies.openssl]

git = "https://github.com/sfackler/rust-openssl"
rev = "8c40c2ef3527fbcf22f11a517422b371b4626852"

[dependencies.phf_mac]

git = "https://github.com/sfackler/rust-phf"
rev = "efc5c5602a4edb2c5b2e9a6178cda65e02e93c59"

