[package]

name = "rust-postgres"
version = "0.10.0"
authors = [ "Steven Fackler <sfackler@gmail.com>" ]

[[lib]]

name = "postgres"
path = "src/lib.rs"

[dependencies.openssl]

git = "https://github.com/sfackler/rust-openssl"
ref = "5fb236128c4c552ace49c2d1f72a8996ee8d05d6"

[dependencies.phf_mac]

git = "https://github.com/sfackler/rust-phf"
ref = "09e8d0a3375af00a08a632922e4024337a58fc57"

