[package]
name = "postgres"
version = "0.8.8"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "A native PostgreSQL driver"
repository = "https://github.com/sfackler/rust-postgres"
documentation = "https://sfackler.github.io/rust-postgres/doc/postgres"
readme = "README.md"
keywords = ["database", "sql"]
build = "build.rs"

[lib]
name = "postgres"
path = "src/lib.rs"
test = false
bench = false

[[test]]
name = "test"
path = "tests/test.rs"

[build-dependencies]
phf_codegen = "0.7"

[dependencies]
bufstream = "0.1"
byteorder = "0.3"
debug-builders = "0.1"
log = "0.3"
phf = "0.7"
rust-crypto = "0.2"
rustc-serialize = "0.3"
openssl = { version = "0.6", optional = true }
serde = { version = "0.3", optional = true }
time = { version = "0.1.14", optional = true }
unix_socket = { version = "0.3", optional = true }
uuid = { version = "0.1", optional = true }

[dev-dependencies]
url = "0.2"
