[workspace]
members = [
    "codegen",
    "postgres",
    "postgres-protocol",
    "postgres-shared",
    "postgres-openssl",
    "postgres-native-tls",
    "tokio-postgres",
    "tokio-postgres-openssl",
]

[patch.crates-io]
tokio-uds = { git = "https://github.com/sfackler/tokio" }
tokio-io = { git = "https://github.com/sfackler/tokio" }
tokio-timer = { git = "https://github.com/sfackler/tokio" }
tokio-codec = { git = "https://github.com/sfackler/tokio" }
tokio-reactor = { git = "https://github.com/sfackler/tokio" }
tokio-executor = { git = "https://github.com/sfackler/tokio" }
