[package]

name = "rust-postgres"
version = "0.0.0"
authors = [ "Steven Fackler <sfackler@gmail.com>" ]

[[lib]]

name = "postgres"
path = "src/lib/lib.rs"

[dependencies.openssl]

git = "https://github.com/sfackler/rust-openssl"
rev = "ad915f13ae2ad4217c18328a618ad696fb7014e1"

[dependencies.phf]

git = "https://github.com/sfackler/rust-phf"
rev = "a0ab8d7f517305c77cdb1d51076ff4b3e31923e5"

[dependencies.phf_mac]

git = "https://github.com/sfackler/rust-phf"
rev = "a0ab8d7f517305c77cdb1d51076ff4b3e31923e5"
