[workspace]
members = [
    "codegen",
    "postgres",
    "postgres-protocol",
    "postgres-shared",
    "tokio-postgres"
]

[patch.crates-io]
socket2 = { git = "https://github.com/sfackler/socket2-rs", branch = "keepalive" }
