[package]
name = "postgres"
version = "0.4.3"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "A native PostgreSQL driver"
repository = "https://github.com/sfackler/rust-postgres"
documentation = "https://sfackler.github.io/doc/postgres"
readme = "README.md"
keywords = ["database", "sql"]

[lib]
name = "postgres"
path = "src/lib.rs"
test = false
bench = false

[[test]]
name = "test"
path = "tests/test.rs"

[features]
default = ["uuid"]

[dependencies]
phf = "0.4"
phf_mac = "0.4"
openssl = "0.2.1"
time = "0.1"
log = "0.1"
rustc-serialize = "0.2"

[dependencies.uuid]
optional = true
version = "0.1"

[dev-dependencies]
url = "0.2"

