[package]
name = "postgres-shared"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[dependencies]
hex = "0.2"
fallible-iterator = "0.1.3"
phf = "=0.7.20"
postgres-protocol = "0.2"
