[package]
name = "postgres-derive-test"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"

[dependencies]
postgres-types = { path = "../postgres-types", features = ["derive"] }
postgres = { path = "../postgres" }
