[package]
name = "postgres-protocol"
version = "0.2.2"
authors = ["Steven Fackler <sfackler@gmail.com>"]
description = "Low level Postgres protocol APIs"
license = "MIT/Apache-2.0"
repository = "https://github.com/sfackler/rust-postgres-protocol"
documentation = "https://docs.rs/postgres-protocol/0.2.2/postgres_protocol"
readme = "../README.md"

[dependencies]
base64 = "0.5"
byteorder = "1.0"
bytes = "0.4"
fallible-iterator = "0.1"
generic-array = "0.7"
hmac = "0.1"
md5 = "0.3"
memchr = "1.0"
rand = "0.3"
sha2 = "0.5"
stringprep = "0.1"
