[package]
name = "postgres"
version = "0.13.5"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "A native PostgreSQL driver"
repository = "https://github.com/sfackler/rust-postgres"
documentation = "https://docs.rs/postgres/0.13.5/postgres"
readme = "../README.md"
keywords = ["database", "postgres", "postgresql", "sql"]
include = ["src/*", "Cargo.toml", "LICENSE", "README.md", "THIRD_PARTY"]

[lib]
name = "postgres"
path = "src/lib.rs"
test = false
bench = false

[[test]]
name = "test"
path = "tests/test.rs"

[features]
with-bit-vec = ["postgres-shared/with-bit-vec"]
with-chrono = ["postgres-shared/with-chrono"]
with-eui48 = ["postgres-shared/with-eui48"]
with-rustc-serialize = ["postgres-shared/with-rustc-serialize"]
with-serde_json = ["postgres-shared/with-serde_json"]
with-time = ["postgres-shared/with-time"]
with-uuid = ["postgres-shared/with-uuid"]

with-openssl = ["openssl"]
with-native-tls = ["native-tls"]
with-schannel = ["schannel"]
with-security-framework = ["security-framework"]

no-logging = []

[dependencies]
bufstream = "0.1"
fallible-iterator = "0.1.3"
hex = "0.2"
log = "0.3"
postgres-protocol = "0.2"

openssl = { version = "0.9.2", optional = true }
native-tls = { version = "0.1", optional = true }
rustc-serialize = { version = "0.3", optional = true }
schannel = { version = "0.1", optional = true }
security-framework = { version = "0.1.2", optional = true }

postgres-shared = { version = "0.1", path = "../postgres-shared" }

[dev-dependencies]
url = "1.0"

bit-vec = "0.4"
chrono = "0.2.14"
eui48 = "0.1"
rustc-serialize = "0.3"
serde_json = ">= 0.6, < 0.10"
time = "0.1.14"
uuid = ">= 0.1, < 0.4"
