[package]
name = "postgres"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"

[features]
default = ["runtime"]

runtime = ["tokio-postgres/runtime", "tokio", "lazy_static", "log"]

[dependencies]
futures = "0.1"
tokio-postgres = { version = "0.3", path = "../tokio-postgres", default-features = false }

tokio = { version = "0.1", optional = true }
lazy_static = { version = "1.0", optional = true }
log = { version = "0.4", optional = true }
